apiVersion: v1
kind: Service
metadata:
  name: drfarah-staging-postgres
  namespace: drfarah-staging
  labels:
    app: drfarah-staging-postgres
spec:
  type: ClusterIP
  selector:
    app: drfarah-staging-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
